"""create_notepad_model

Revision ID: c52e045b1814
Revises: 001
Create Date: 2026-09-21 01:28:51.633718

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c52e045b1814'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notepad', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('notepad_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('title')
        batch_op.drop_column('body')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notepad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('body', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(length=256), nullable=False))
        batch_op.create_foreign_key(batch_op.f('notepad_ibfk_1'), 'user', ['user_id'], ['id'])

    op.drop_table('webhook')
    # ### end Alembic commands ###
